version: '3'

dotenv: ['.env']

tasks:
  client:
    cmds:
      - go build -o ./bin/client ./client/main.go
      - ./bin/client
  
  server:
    cmds:
      - go build -o bin/server server/main.go
      - ./bin/server
